### ISSUE TITLE
Look at tutorials

### ISSUE THREAD

**Issue by DevMagicLord** [deprecated-armory3d/armory_tutorials_b27#2]
There should be a very usefull tutorial look at with two examples.

1) Object look at another object we can move anywhere, using the Z axis as rotation axis.
This is used in every game alsmot.
 
2) Same as above with speed interpolation, for example an object rotating slowly to face another object, using the shortest angle.

2) One object looking at another object on Z and X axis, this could be some mechanic object on floor rotating on two axes and able to lock and follow a moving object.

**Comment by luboslenco** [comment]
Sounds good. There is some relevant code at [NavMesh.hx](https://github.com/armory3d/armory/blob/master/Sources/armory/trait/NavAgent.hx), will turn it into a very useful tutorial.:)

**Comment by DevMagicLord** [comment]
Good.

**Comment by luboslenco** [comment]
Will move this issue to the repository at https://github.com/armory3d/armory_tutorials.
